language: java

jdk:
  - oraclejdk8
  - oraclejdk7

os:
  - linux
  - windows

branches:
  only:
    - master
    
before_install:
 - chmod +x gradlew

 
before_script:
 - sudo pip install codecov
 
after_success:
 - codecov
